version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - ./data:/bitnami/zookeeper/data # Persist Zookeeper data
      - ./datalog:/bitnami/zookeeper/datalog # Persist Zookeeper transaction logs
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Enable anonymous login (no authentication)

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092" # Kafka port
    volumes:
      - ./data:/bitnami/kafka/data # Persist Kafka data
      - ./logs:/bitnami/kafka/logs # Persist Kafka logs
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 # Replace 'localhost' with your server's IP or hostname
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes # Enable plaintext listener for development purposes
    depends_on:
      - zookeeper

  auth_service:
    container_name: auth_service
    build: ./authetication-service
    ports:
      - 3000:3000
    volumes:
      - ./authetication-service:/app
    depends_on:
      - kafka

  admin_service:
    container_name: admin_service
    build: ./admin-service
    ports:
      - 4000:4000
    volumes:
      - ./admin-service:/app
    depends_on:
      - kafka

