FROM nginx:latest
# COPY ssl/cert1.crt /etc/nginx/ssl/cert1.crt
# COPY ssl/cert1.key /etc/nginx/ssl/cert1.key
# COPY ssl/cert2.crt /etc/nginx/ssl/cert2.crt
# COPY ssl/cert2.key /etc/nginx/ssl/cert2.key
# COPY ssl/cert3.crt /etc/nginx/ssl/cert3.crt
# COPY ssl/cert3.key /etc/nginx/ssl/cert3.key
COPY nginx.conf /etc/nginx/nginx.conf

# EXPOSE 80
# EXPOSE 443

# CMD ["nginx", "-g", "daemon off;"]
